autoreconf: error: /usr/bin/autoconf failed with exit status: 1
  STDERR:
# Command failed: ['/opt/hostedtoolcache/Python/3.9.23/x64/bin/python', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=shuangseqiu', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/runner/work/shuangseqiu-app/shuangseqiu-app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SELENIUM_JAR_PATH = '/usr/share/java/selenium-server.jar'
#     CONDA = '/usr/share/miniconda'
#     GITHUB_WORKSPACE = '/home/runner/work/shuangseqiu-app/shuangseqiu-app'
#     JAVA_HOME_11_X64 = '/usr/lib/jvm/temurin-11-jdk-amd64'
#     PKG_CONFIG_PATH = '/opt/hostedtoolcache/Python/3.9.23/x64/lib/pkgconfig'
#     GITHUB_PATH = '/home/runner/work/_temp/_runner_file_commands/add_path_3a36cf1d-743e-490d-adfb-b34278c7588a'
#     GITHUB_ACTION = '__run_3'
#     JAVA_HOME = '/usr/lib/jvm/temurin-17-jdk-amd64'
#     GITHUB_RUN_NUMBER = '5'
#     RUNNER_NAME = 'GitHub Actions 1000000003'
#     GRADLE_HOME = '/usr/share/gradle-9.1.0'
#     GITHUB_REPOSITORY_OWNER_ID = '235072418'
#     ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE = '/opt/actionarchivecache'
#     XDG_CONFIG_HOME = '/home/runner/.config'
#     Python_ROOT_DIR = '/opt/hostedtoolcache/Python/3.9.23/x64'
#     MEMORY_PRESSURE_WRITE = 'c29tZSAyMDAwMDAgMjAwMDAwMAA='
#     DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
#     ANT_HOME = '/usr/share/ant'
#     JAVA_HOME_8_X64 = '/usr/lib/jvm/temurin-8-jdk-amd64'
#     GITHUB_TRIGGERING_ACTOR = 'shengyusn-dotcom'
#     pythonLocation = '/opt/hostedtoolcache/Python/3.9.23/x64'
#     GITHUB_REF_TYPE = 'branch'
#     HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS = '3650'
#     ANDROID_NDK = '/usr/local/lib/android/sdk/ndk/27.3.13750724'
#     BOOTSTRAP_HASKELL_NONINTERACTIVE = '1'
#     PWD = '/home/runner/work/shuangseqiu-app/shuangseqiu-app'
#     PIPX_BIN_DIR = '/opt/pipx_bin'
#     LOGNAME = 'runner'
#     GITHUB_REPOSITORY_ID = '1066300486'
#     GITHUB_ACTIONS = 'true'
#     ANDROID_NDK_LATEST_HOME = '/usr/local/lib/android/sdk/ndk/28.2.13676358'
#     SYSTEMD_EXEC_PID = '1898'
#     GITHUB_SHA = 'a8817f0fd992c5b8971d100af2f6b362bcf42082'
#     GITHUB_WORKFLOW_REF = 'shengyusn-dotcom/shuangseqiu-app/.github/workflows/build.yml@refs/heads/main'
#     POWERSHELL_DISTRIBUTION_CHANNEL = 'GitHub-Actions-ubuntu24'
#     RUNNER_ENVIRONMENT = 'github-hosted'
#     DOTNET_MULTILEVEL_LOOKUP = '0'
#     GITHUB_REF = 'refs/heads/main'
#     RUNNER_OS = 'Linux'
#     GITHUB_REF_PROTECTED = 'false'
#     HOME = '/home/runner'
#     GITHUB_API_URL = 'https://api.github.com'
#     LANG = 'C.UTF-8'
#     RUNNER_TRACKING_ID = 'github_2eca3560-f8d3-4dfc-8507-d50f0a0aaf89'
#     RUNNER_ARCH = 'X64'
#     MEMORY_PRESSURE_WATCH = '/sys/fs/cgroup/system.slice/hosted-compute-agent.service/memory.pressure'
#     RUNNER_TEMP = '/home/runner/work/_temp'
#     GITHUB_STATE = '/home/runner/work/_temp/_runner_file_commands/save_state_3a36cf1d-743e-490d-adfb-b34278c7588a'
#     EDGEWEBDRIVER = '/usr/local/share/edge_driver'
#     JAVA_HOME_21_X64 = '/usr/lib/jvm/temurin-21-jdk-amd64'
#     GITHUB_ENV = '/home/runner/work/_temp/_runner_file_commands/set_env_3a36cf1d-743e-490d-adfb-b34278c7588a'
#     GITHUB_EVENT_PATH = '/home/runner/work/_temp/_github_workflow/event.json'
#     INVOCATION_ID = '65f122e5bbd840b4a895ae47912a3974'
#     GITHUB_EVENT_NAME = 'push'
#     GITHUB_RUN_ID = '18093427285'
#     JAVA_HOME_17_X64 = '/usr/lib/jvm/temurin-17-jdk-amd64'
#     ANDROID_NDK_HOME = '/usr/local/lib/android/sdk/ndk/27.3.13750724'
#     GITHUB_STEP_SUMMARY = '/home/runner/work/_temp/_runner_file_commands/step_summary_3a36cf1d-743e-490d-adfb-b34278c7588a'
#     HOMEBREW_NO_AUTO_UPDATE = '1'
#     GITHUB_ACTOR = 'shengyusn-dotcom'
#     NVM_DIR = '/home/runner/.nvm'
#     SGX_AESM_ADDR = '1'
#     GITHUB_RUN_ATTEMPT = '1'
#     ANDROID_HOME = '/usr/local/lib/android/sdk'
#     GITHUB_GRAPHQL_URL = 'https://api.github.com/graphql'
#     ACCEPT_EULA = 'Y'
#     USER = 'runner'
#     GITHUB_SERVER_URL = 'https://github.com'
#     PIPX_HOME = '/opt/pipx'
#     GECKOWEBDRIVER = '/usr/local/share/gecko_driver'
#     CHROMEWEBDRIVER = '/usr/local/share/chromedriver-linux64'
#     SHLVL = '1'
#     ANDROID_SDK_ROOT = '/usr/local/lib/android/sdk'
#     VCPKG_INSTALLATION_ROOT = '/usr/local/share/vcpkg'
#     GITHUB_ACTOR_ID = '235072418'
#     RUNNER_TOOL_CACHE = '/opt/hostedtoolcache'
#     ImageVersion = '20250922.53.1'
#     Python3_ROOT_DIR = '/opt/hostedtoolcache/Python/3.9.23/x64'
#     DOTNET_NOLOGO = '1'
#     GOROOT_1_23_X64 = '/opt/hostedtoolcache/go/1.23.12/x64'
#     GITHUB_WORKFLOW_SHA = 'a8817f0fd992c5b8971d100af2f6b362bcf42082'
#     GOROOT_1_24_X64 = '/opt/hostedtoolcache/go/1.24.7/x64'
#     GITHUB_REF_NAME = 'main'
#     GITHUB_JOB = 'build'
#     LD_LIBRARY_PATH = '/opt/hostedtoolcache/Python/3.9.23/x64/lib'
#     XDG_RUNTIME_DIR = '/run/user/1001'
#     AZURE_EXTENSION_DIR = '/opt/az/azcliextensions'
#     GITHUB_REPOSITORY = 'shengyusn-dotcom/shuangseqiu-app'
#     Python2_ROOT_DIR = '/opt/hostedtoolcache/Python/3.9.23/x64'
#     GOROOT_1_22_X64 = '/opt/hostedtoolcache/go/1.22.12/x64'
#     CHROME_BIN = '/usr/bin/google-chrome'
#     ANDROID_NDK_ROOT = '/usr/local/lib/android/sdk/ndk/27.3.13750724'
#     GITHUB_RETENTION_DAYS = '90'
#     JOURNAL_STREAM = '9:11116'
#     RUNNER_WORKSPACE = '/home/runner/work/shuangseqiu-app'
#     GITHUB_ACTION_REPOSITORY = ''
#     PATH = '/home/runner/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/hostedtoolcache/Python/3.9.23/x64/bin:/opt/hostedtoolcache/Python/3.9.23/x64:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     GITHUB_BASE_REF = ''
#     GHCUP_INSTALL_BASE_PREFIX = '/usr/local'
#     CI = 'true'
#     SWIFT_PATH = '/usr/share/swift/usr/bin'
#     ImageOS = 'ubuntu24'
#     GITHUB_REPOSITORY_OWNER = 'shengyusn-dotcom'
#     GITHUB_HEAD_REF = ''
#     GITHUB_ACTION_REF = ''
#     ENABLE_RUNNER_TRACING = 'true'
#     GITHUB_WORKFLOW = 'Build Android APK'
#     DEBIAN_FRONTEND = 'noninteractive'
#     GITHUB_OUTPUT = '/home/runner/work/_temp/_runner_file_commands/set_output_3a36cf1d-743e-490d-adfb-b34278c7588a'
#     AGENT_TOOLSDIRECTORY = '/opt/hostedtoolcache'
#     _ = '/opt/hostedtoolcache/Python/3.9.23/x64/bin/buildozer'
#     PACKAGES_PATH = '/home/runner/.buildozer/android/packages'
#     ANDROIDSDK = '/home/runner/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/runner/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '33'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
Error: Process completed with exit code 1.
